# Prop Configuration File
# This file contains thresholds and settings for different prop types

kills:
  min_value: 0
  max_value: 20
  impossible_threshold: 15
  low_threshold_factor: 0.5
  high_threshold_factor: 1.5

assists:
  min_value: 0
  max_value: 25
  impossible_threshold: 20
  low_threshold_factor: 0.5
  high_threshold_factor: 1.5

cs:
  min_value: 0
  max_value: 400
  impossible_threshold: 300
  low_threshold_factor: 0.6
  high_threshold_factor: 1.4

deaths:
  min_value: 0
  max_value: 10
  impossible_threshold: 8
  low_threshold_factor: 0.7
  high_threshold_factor: 1.3

gold:
  min_value: 0
  max_value: 20000
  impossible_threshold: 15000
  low_threshold_factor: 0.6
  high_threshold_factor: 1.4

damage:
  min_value: 0
  max_value: 30000
  impossible_threshold: 25000
  low_threshold_factor: 0.6
  high_threshold_factor: 1.4 